### ISSUE TITLE
Why moving to PureScript?

### ISSUE THREAD

**Issue by kokizzu** [atomicits/elm-react-native#49]
I am curious, why move from elm to PureScript?

**Comment by sudhirvkumar** [comment]
@kokizzu elm is simple and easy and has a "The Elm Architecture" when we are working on a complex project, we end up writing a lot of boiler plate code. PureScript JsonDecode and JsonEncode code is super simple and easy! Elm not so!

PureScript, is perfect for us as it supports TypeClasses, Higher Kinded Types etc.

Also, the most important thing is... PureScript compiles to JavaScript and what we do with that is up to us. Elm is very focus on UI. Elm is more an UI library rather than a general programming language!

**Comment by pietro909** [comment]
Hey, you might want to add this answer to the Readme so that the people will figure it out... I was about opening the same "issue" :-)

**Comment by sudhirvkumar** [comment]
@pietro909 sure! Thanks for the suggestion.
